harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
description: cv-canary
envName: kubemini
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - z25IpXiKSO2QhfdIgtMnNQ
templatized: false
