harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
description: cv-canary
envName: kubemini
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - z25IpXiKSO2QhfdIgtMnNQ
phases:
- type: KUBERNETES
  computeProviderName: MiniKube
  daemonSet: false
  infraDefinitionName: minikube2
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '1'
    - type: PROMETHEUS
      name: Prometheus
      properties:
        analysisServerConfigId: 5nNLiri8SJi1pa-3LRirqg
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_CURRENT
        customThresholdRefId: a7c4277dc696460eac85c16f46366f1c
        timeDuration: 5
        timeSeriesToAnalyze:
        - metricName: normal_call
          metricType: THROUGHPUT
          txnName: Custom
          url: io_harness_custom_metric_normal_call{kubernetes_pod_name="$hostName"}
        - metricName: error_call
          metricType: ERROR
          txnName: Custom
          url: io_harness_custom_metric_error_call{kubernetes_pod_name="$hostName"}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: cv-deploy
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: MiniKube
  daemonSet: false
  infraDefinitionName: minikube2
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DELETE
      name: Delete
      properties:
        deleteNamespacesForRelease: false
        resources: ${k8s.canaryWorkload}
        stateTimeoutInMinutes: 10
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: cv-deploy
  statefulSet: false
templatized: false
